CREATE TABLE IF NOT EXISTS zno(
        out_id                    char(100),
        birth                     int,
        sex                       char(20),
        region                    char(100),
        area_name                 char(100),
        ter_name                  char(100),
        reg_type_name             char(300),
        ter_type_name             char(100),
        class_prof_name           char(100),
        class_lang_name           char(100),
        eo_name                   char(300),
        eo_type_name              char(100),
        eo_reg_name               char(50),
        eo_area_name              char(50),
        eo_ter_name               char(50),
        eo_parent                 char(300),
        ukr_test                  char(50),
        ukr_sub_test              char(50),
        ukr_status                char(30),
        ukr_ball_100              decimal(15, 2),
        ukr_ball_12               int,
        ukr_ball                  decimal(15, 2),
        ukr_adapt_scale           int,
        ukr_pt_name               char(300),
        ukr_pt_reg                char(50),
        ukr_pt_area               char(50),
        ukr_pt_ter                char(50),
        uml_test                  char(50),
        uml_status                char(50),
        uml_ball_100              decimal(15, 2),
        uml_ball_12               int,
        uml_ball                  decimal(15, 2),
        uml_adapt_scale           int,
        uml_pt_name               char(300),
        uml_pt_reg                char(50),
        uml_pt_area               char(50),
        uml_pt_ter                char(50),
        hist_test                 char(50),
        hist_lang                 char(50),
        hist_status               char(50),
        hist_ball_100             decimal(15, 2),
        hist_ball_12              int,
        hist_ball                 decimal(15, 2),
        hist_pt_name              char(250),
        hist_pt_reg               char(50),
        hist_pt_area              char(50),
        hist_pt_ter               char(50),
        math_test                 char(50),
        math_lang                 char(50),
        math_status               char(50),
        math_ball_100             decimal(15, 2),
        math_ball_12              int,
        math_dpa_level            char(50),
        math_ball                 decimal(15, 2),
        math_pt_name              char(250),
        math_pt_reg               char(50),
        math_pt_area              char(50),
        math_pt_ter               char(50),
        physics_test              char(50),
        physics_lang              char(50),
        physics_status            char(50),
        physics_ball_100          decimal(15, 2),
        physics_ball_12           int,
        physics_ball              decimal(15, 2),
        physics_pt_name           char(300),
        physics_pt_reg            char(50),
        physics_pt_area           char(50),
        physics_pt_ter            char(50),
        chem_test                 char(50),
        chem_lang                 char(50),
        chem_status               char(50),
        chem_ball_100             decimal(15, 2),
        chem_ball_12              int,
        chem_ball                 decimal(15, 2),
        chem_pt_name              char(250),
        chem_pt_reg               char(50),
        chem_pt_area              char(50),
        chem_pt_ter               char(50),
        bio_test                  char(50),
        bio_lang                  char(50),
        bio_status                char(50),
        bio_ball_100              decimal(15, 2),
        bio_ball_12               int,
        bio_ball                  decimal(15, 2),
        bio_pt_name               char(250),
        bio_pt_reg                char(50),
        bio_pt_area               char(50),
        bio_pt_ter                char(50),
        geo_test                  char(50),
        geo_lang                  char(50),
        geo_status                char(50),
        geo_ball_100              decimal(15, 2),
        geo_ball_12               int,
        geo_ball                  decimal(15, 2),
        geo_pt_name               char(250),
        geo_pt_reg                char(50),
        geo_pt_area               char(50),
        geo_pt_ter                char(50),
        eng_test                  char(50),
        eng_lang                  char(50),
        eng_status                char(50),
        eng_ball_100              decimal(15, 2),
        eng_ball_12               int,
        eng_dpa_level             char(50),
        eng_ball                  decimal(15, 2),
        eng_pt_name               char(250),
        eng_pt_reg                char(50),
        eng_pt_area               char(50),
        eng_pt_ter                char(50),
        fra_test                  char(50),
        fra_lang                  char(50),
        fra_status                char(50),
        fra_ball_100              decimal(15, 2),
        fra_ball_12               int,
        fra_dpa_level             char(50),
        fra_ball                  decimal(15, 2),
        fra_pt_name               char(250),
        fra_pt_reg                char(50),
        fra_pt_area               char(50),
        fra_pt_ter                char(50),
        deu_test                  char(50),
        deu_lang                  char(50),
        deu_status                char(50),
        deu_ball_100              decimal(15, 2),
        deu_ball_12               int,
        deu_dpa_level             char(50),
        deu_ball                  decimal(15, 2),
        deu_pt_name               char(250),
        deu_pt_reg                char(50),
        deu_pt_area               char(50),
        deu_pt_ter                char(50),
        spa_test                  char(50),
        spa_lang                  char(50),
        spa_status                char(50),
        spa_ball_100              decimal(15, 2),
        spa_ball_12               int,
        spa_dpa_level             char(50),
        spa_ball                  decimal(15, 2),
        spa_pt_name               char(250),
        spa_pt_reg                char(50),
        spa_pt_area               char(50),
        spa_pt_ter                char(50),
        year                      int
);